blank_issues_enabled: true
contact_links:
  - name: ğŸ™ General questions & help
    url: https://github.com/brndnmtthws/conky/discussions/categories/q-a
    about: Please ask and answer general questions using GitHub Discussions
  - name: ğŸ’¡ New ideas and feature requests
    url: https://github.com/brndnmtthws/conky/discussions/categories/ideas
    about: Request and discuss enhancements using GitHub Discussions
